feat(blog): you should use node test act one
mateonunez/website pull request #396
Opened 2024-01-07 13:34 UTC by mateonunez

Act One.

2024-01-07 13:37 UTC, mateonunez commented
Hey folks! I finally found time to prepare a draft of Act One.

This part is very introductory and contains few technical aspects and few features. In Act Two, we will go more technical.

cc @airscripts, @paolapog, @KristianLentino99

2024-01-07 17:52 UTC, paolapog requested changes
Great article 💪🏻 just a small typo
Sorry if it's not clear where is the typo, I'm on the train right now

2024-01-07 17:52 UTC, paolapog commented on articles/you-should-use-node-test-act-one.mdx
> +The **Act One** consists of a brief introduction to the `node:test` moudle and some basic concepts that you should know before starting to use it.
Typo, should be module and not moudle

2024-01-08 09:15 UTC, paolapog approved these changes

2024-01-08 18:57 UTC, merged